[[keymaps]]
    command = "split_close"
    key     = "Ctrl+Shift+W"
    mode    = "i"

[[keymaps]]
    command = "-split_close"
    key     = "Ctrl+W"
    mode    = "i"

[[keymaps]]
    command = "close_window_tab"
    key     = "Ctrl+W"

[[keymaps]]
    command = "close_terminal_tab"
    key     = "Shift+Escape"
