"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
command_timeout = 750
continuation_prompt = "[\uf101](bright-black) "
format = """
$username\
$hostname\
[\ue0b0](fg:bright-yellow bg:green)\
$directory\
$rust\
$python\
$dotnet\
$haskell\
$php\
$nodejs\
$c\
$kotlin\
$lua\
$ruby\
$zig\
$git_branch\
$git_status\
[\ue0b0](fg:bright-blue bg:bright-yellow)\
[\ue0b0](fg:bright-yellow bg:none)\
$fill\
$cmd_duration\
$fill\
$time
$character
"""
right_format = ""
scan_timeout = 90

[username]
    format      = "[\ue0b0 ](fg:bright-black bg:green)[$user ]($style)[\ue0b0](fg:green bg:bright-yellow)"
    show_always = true
    style_root  = "fg:bright-green bg:bright-purple bold"
    style_user  = "fg:purple bg:green bold"

[hostname]
    format   = "[ \uf1fa $hostname$ssh_symbol ]($style)"
    ssh_only = true
    style    = "bg:bright-yellow fg:bright-black bold"

[directory]
    format           = "[ $path ]($style)[$read_only]($style)[\ue0b0](fg:green bg:yellow)[\ue0b0](fg:yellow bg:bright-blue)"
    home_symbol      = "\ueb06 "
    read_only        = "\uf8ee "
    style            = "bg:green fg:bright-blue bold"
    use_logical_path = true
    use_os_path_sep  = false

[directory.substitutions]
    "C:/msys64/home/Martin" = "\ueb06 "
    "C:/msys64/home/Riven"  = "\ueb06 "
    "C:/msys64/home/martin" = "\ueb06 "
    "C:/msys64/home/riven"  = "\ueb06 "

# Programming language hell
[c]
    format = "[ $symbol ($version)]($style)[\ue0b0](fg:green bg:bright-blue inverted)[\ue0b0](fg:green bg:bright-blue)"
    style  = "bg:bright-blue fg:black bold"
    symbol = "\ufb70"

[dotnet]
    format = "[ $symbol ($version)]($style)[\ue0b0](fg:green bg:bright-blue inverted)[\ue0b0](fg:green bg:bright-blue)"
    style  = "bg:bright-blue fg:black bold"
    symbol = "\uf81a"

[haskell]
    format = "[ $symbol ($version)]($style)[\ue0b0](fg:green bg:bright-blue inverted)[\ue0b0](fg:green bg:bright-blue)"
    style  = "bg:bright-blue fg:black bold"
    symbol = "\ue61f"

[kotlin]
    format = "[ $symbol ($version)]($style)[\ue0b0](fg:green bg:bright-blue inverted)[\ue0b0](fg:green bg:bright-blue)"
    style  = "bg:bright-blue fg:black bold"
    symbol = "\ue634"

[lua]
    format = "[ $symbol ($version)]($style)[\ue0b0](fg:green bg:bright-blue inverted)[\ue0b0](fg:green bg:bright-blue)"
    style  = "bg:bright-blue fg:black bold"
    symbol = "\ue620"

[nodejs]
    format = "[ $symbol ($version)]($style)[\ue0b0](fg:green bg:bright-blue inverted)[\ue0b0](fg:green bg:bright-blue)"
    style  = "bg:bright-blue fg:black bold"
    symbol = "\uf898"

[php]
    format = "[ $symbol ($version)]($style)[\ue0b0](fg:green bg:bright-blue inverted)[\ue0b0](fg:green bg:bright-blue)"
    style  = "bg:bright-blue fg:black bold"
    symbol = "\ue608"

[python]
    format = "[ $symbol ($version)]($style)[\ue0b0](fg:green bg:bright-blue inverted)[\ue0b0](fg:green bg:bright-blue)"
    style  = "bg:bright-blue fg:black bold"
    symbol = "\ue606"

[ruby]
    format = "[ $symbol ($version)]($style)[\ue0b0](fg:green bg:bright-blue inverted)[\ue0b0](fg:green bg:bright-blue)"
    style  = "bg:bright-blue fg:black bold"
    symbol = "\ue739"

[rust]
    format = "[ $symbol ($version)]($style)[\ue0b0](fg:green bg:bright-blue inverted)[\ue0b0](fg:green bg:bright-blue)"
    style  = "bg:bright-blue fg:black bold"
    symbol = "\ue7a8"

[zig]
    format = "[ $symbol ($version)]($style)[\ue0b0](fg:green bg:bright-blue inverted)[\ue0b0](fg:green bg:bright-blue)"
    style  = "bg:bright-blue fg:black bold"
    symbol = "\ue6a9"

[git_branch]
    format = "[ on $symbol$branch(:$remote_branch) ]($style)"
    style  = "bg:bright-blue fg:bright-black bold"
    symbol = "\ue0a0"

[git_status]
    ahead      = "\uf176"
    behind     = "\uf175"
    deleted    = "\uef90"
    diverged   = "\uf09f"
    format     = "[\\[$all_status$ahead_behind\\]]($style)"
    renamed    = "\uf101"
    style      = "bg:bright-blue fg:bright-black bold"
    up_to_date = "\uebb1"

[fill]
    symbol = " "

[cmd_duration]
    format            = "[\ue0b3](fg:bright-blue bg:none)[$duration]($style)[\ue0b1](fg:bright-blue bg:none)"
    min_time          = 750
    show_milliseconds = true
    style             = "bg:bright-blue fg:green bold"

[time]
    disabled    = false
    format      = "[\ue0b3](fg:purple bg:none)[$time]($style)[\ue0b2](fg:bright-black bg:purple)"
    style       = "bg:purple fg:bright-red bold"
    time_format = " at %I:%M:%S %p on %d-%m-%Y "
    use_12hr    = true
