"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
command_timeout = 750
continuation_prompt = "[\uf101](bright-black) "
format = """
$username\
$hostname\
[\ue0b0](fg:cyan bg:bright-green)\
$directory\
$rust\
$python\
$dotnet\
$haskell\
$php\
$nodejs\
$c\
$kotlin\
$lua\
$ruby\
$zig\
$golang\
$git_branch\
$git_status\
[\ue0b0](fg:bright-blue bg:bright-yellow)\
[\ue0b0](fg:bright-yellow bg:none)\
$fill\
$cmd_duration\
$fill\
$time
$character
"""
right_format = ""
scan_timeout = 90

[username]
    format      = "[\ue0b0 ](fg:bright-black bg:bright-green)[$user ]($style)[\ue0b0](fg:bright-green bg:cyan)"
    show_always = true
    style_root  = "fg:black bg:bright-red bold"
    style_user  = "fg:black bg:bright-green bold"

[hostname]
    format   = "[ \uf1fa $hostname$ssh_symbol ]($style)"
    ssh_only = true
    style    = "bg:cyan fg:bright-black bold"

[directory]
    format           = "[ $path ]($style)[$read_only]($style)[\ue0b0](fg:bright-green bg:cyan)[\ue0b0](fg:cyan bg:bright-blue)"
    home_symbol      = "\ueb06 "
    read_only        = "\uf8ee "
    style            = "bg:bright-green fg:red bold"
    use_logical_path = true
    use_os_path_sep  = false

    [directory.substitutions]
        "C:/msys64/home/Martin" = "\ueb06 "
        "C:/msys64/home/Riven"  = "\ueb06 "
        "C:/msys64/home/martin" = "\ueb06 "
        "C:/msys64/home/riven"  = "\ueb06 "

# Programming language hell
[c]
    format = "[ $symbol ($version)]($style)[\ue0b0](fg:green bg:bright-blue inverted)[\ue0b0](fg:green bg:bright-blue)"
    style  = "bg:bright-blue fg:black bold"
    symbol = "\ue61e"

[dotnet]
    format = "[ $symbol ($version)]($style)[\ue0b0](fg:green bg:bright-blue inverted)[\ue0b0](fg:green bg:bright-blue)"
    style  = "bg:bright-blue fg:black bold"
    symbol = "\ue648"

[golang]
    format = "[ $symbol ($version)]($style)[\ue0b0](fg:green bg:bright-blue inverted)[\ue0b0](fg:green bg:bright-blue)"
    style  = "bg:bright-blue fg:black bold"
    symbol = "\ue65e"

[haskell]
    format = "[ $symbol ($version)]($style)[\ue0b0](fg:green bg:bright-blue inverted)[\ue0b0](fg:green bg:bright-blue)"
    style  = "bg:bright-blue fg:black bold"
    symbol = "\ue61f"

[kotlin]
    format = "[ $symbol ($version)]($style)[\ue0b0](fg:green bg:bright-blue inverted)[\ue0b0](fg:green bg:bright-blue)"
    style  = "bg:bright-blue fg:black bold"
    symbol = "\ue634"

[lua]
    format = "[ $symbol ($version)]($style)[\ue0b0](fg:green bg:bright-blue inverted)[\ue0b0](fg:green bg:bright-blue)"
    style  = "bg:bright-blue fg:black bold"
    symbol = "\ue620"

[nodejs]
    format = "[ $symbol ($version)]($style)[\ue0b0](fg:green bg:bright-blue inverted)[\ue0b0](fg:green bg:bright-blue)"
    style  = "bg:bright-blue fg:black bold"
    symbol = "\ue60c"

[php]
    format = "[ $symbol ($version)]($style)[\ue0b0](fg:green bg:bright-blue inverted)[\ue0b0](fg:green bg:bright-blue)"
    style  = "bg:bright-blue fg:black bold"
    symbol = "\ued6d"

[python]
    format = "[ $symbol ($version)]($style)[\ue0b0](fg:green bg:bright-blue inverted)[\ue0b0](fg:green bg:bright-blue)"
    style  = "bg:bright-blue fg:black bold"
    symbol = "\ue73c"

[ruby]
    format = "[ $symbol ($version)]($style)[\ue0b0](fg:green bg:bright-blue inverted)[\ue0b0](fg:green bg:bright-blue)"
    style  = "bg:bright-blue fg:black bold"
    symbol = "\ue23e"

[rust]
    format = "[ $symbol ($version)]($style)[\ue0b0](fg:green bg:bright-blue inverted)[\ue0b0](fg:green bg:bright-blue)"
    style  = "bg:bright-blue fg:black bold"
    symbol = "\ue7a8"

[zig]
    format = "[ $symbol ($version)]($style)[\ue0b0](fg:green bg:bright-blue inverted)[\ue0b0](fg:green bg:bright-blue)"
    style  = "bg:bright-blue fg:black bold"
    symbol = "\ue6a9"

# End of programming languages

[git_branch]
    format = "[ on $symbol$branch(:$remote_branch) ]($style)"
    style  = "bg:bright-blue fg:bright-black bold"
    symbol = "\ue0a0"

[git_status]
    ahead      = "\uf176"
    behind     = "\uf175"
    deleted    = "\uf1f8"
    diverged   = "\uf09f"
    format     = "[\\[$all_status$ahead_behind\\]]($style)"
    renamed    = "\uf101"
    style      = "bg:bright-blue fg:bright-black bold"
    up_to_date = "\uebb1"

[fill]
    symbol = " "

[cmd_duration]
    format            = "[\ue0b3](fg:bright-blue bg:none)[ $duration ]($style)[\ue0b1](fg:bright-blue bg:none)"
    min_time          = 750
    show_milliseconds = true
    style             = "bg:bright-blue fg:bright-black bold"

[time]
    disabled    = false
    format      = "[\ue0b3](fg:purple bg:none)[$time]($style)[\ue0b2](fg:bright-black bg:bright-purple)"
    style       = "bg:bright-purple fg:black bold"
    time_format = " at %I:%M:%S %p "
    use_12hr    = true
